name: Deploy to Demo

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.KENJI_MIRAI_FIRST_CONOHA_SERVER_SECRET_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no c3801632@160.251.71.121 -p 8022 "cd public_html/demo.cystarbucks.com/starbucks-customize-app && pwd && ls -l"
#        ssh -o StrictHostKeyChecking=no c3801632@160.251.71.121 -p 8022 "cd public_html/demo.cystarbucks.com/starbucks-customize-app && git pull origin develop"
