name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.KENJI_FIRST_CONOHA }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no c3801632@www315.conoha.ne.jp -p 8022 \
        "cd public_html/cystarbucks.com/starbucks-customize-app && git fetch -p && git pull origin main"
